export type SiteConfig = typeof siteConfig;

export const siteConfig = {
  name: '女仆阁',
  description: '在线流媒体使用M3U8格式给您更快的加载体验国产传媒,华人人AV.',
  keywords: [
    '国产传媒',
    '华人AV',
    'onlyfans',
    '福利合集',
    '台湾传媒',
    '香港传媒',
    '欧美传媒',
    '糖心VLOG',
    '兔子先生',
    '麻豆视频',
    'Ed Mosaic',
    '蜜桃传媒',
    '皇家华人',
    '蜜桃传媒',
    '萝莉社',
    '葫芦影业',
  ],
  authors: [{ name: 'John Doe', url: 'https://npg0.ru' }],
  creator: '女仆阁的视频团队',
  navItems: [
    {
      label: '首页',
      href: '/',
    },
    {
      label: '国产传媒',
      href: '/chuan-mei',
    },
    {
      label: 'onlyfans',
      href: '/onlyfans',
    },
    {
      label: '国外视频',
      href: '/guo-wai',
    },
    {
      label: '其他合集',
      href: '/he-ji',
    },
  ],
  navMenuItems: [
    { label: '糖心VLOG', href: '/chuan-mei/糖心VLOG' },
    { label: '兔子先生', href: '/chuan-mei/兔子先生' },
    { label: '麻豆视频', href: '/chuan-mei/麻豆视频' },
    { label: 'Ed Mosaic', href: '/chuan-mei/Ed Mosaic' },
    { label: '蜜桃传媒', href: '/chuan-mei/蜜桃传媒' },
    { label: '皇家华人', href: '/chuan-mei/皇家华人' },
    { label: '萝莉社', href: '/chuan-mei/萝莉社' },
    { label: '葫芦影业', href: '/chuan-mei/葫芦影业' },
    { label: '天美传媒', href: '/chuan-mei/天美传媒' },
    { label: '扣扣传媒', href: '/chuan-mei/扣扣传媒' },
    { label: '大象传媒', href: '/chuan-mei/大象传媒' },
    { label: '91制片厂', href: '/chuan-mei/91制片厂' },
    { label: '肉肉传媒', href: '/chuan-mei/肉肉传媒' },
    { label: '性视界', href: '/chuan-mei/性视界' },
    { label: '起点传媒', href: '/chuan-mei/起点传媒' },
    { label: '乌托邦', href: '/chuan-mei/乌托邦' },
    { label: '杏吧传媒', href: '/chuan-mei/杏吧传媒' },
    { label: '冠希传媒', href: '/chuan-mei/冠希传媒' },
    { label: '果冻传媒', href: '/chuan-mei/果冻传媒' },
    { label: '蝌蚪传媒', href: '/chuan-mei/蝌蚪传媒' },
    { label: '爱豆传媒', href: '/chuan-mei/爱豆传媒' },
    { label: '绝对领域', href: '/chuan-mei/绝对领域' },
    { label: '精东传媒', href: '/chuan-mei/精东传媒' },
    { label: '猫爪影像', href: '/chuan-mei/猫爪影像' },
    { label: '爱神传媒', href: '/chuan-mei/爱神传媒' },
    { label: '星空无限', href: '/chuan-mei/星空无限' },
    { label: '越南博主', href: '/onlyfans/越南博主' },
    { label: '台湾博主', href: '/onlyfans/台湾博主' },
    { label: '内地博主', href: '/onlyfans/内地博主' },
    { label: '香港博主', href: '/onlyfans/香港博主' },
    { label: '欧美博主', href: '/onlyfans/欧美博主' },
  ],
  links: {
    github: '/',
    twitter: '/',
    docs: '/',
    discord: '/',
    sponsor: '/',
  },
  friendLinks: [
    {
      label: '绿色小导航',
      href: 'https://玽zj鎊.greendh.link/%e7%a3%a320',
    },
    {
      label: '找AV导航',
      href: 'https://va.zavdh.cc/gs4osh',
    },
    {
      label: '蓝色导航',
      href: 'https://lt.bluedaohang.club/d33vfa',
    },
    {
      label: '色界吧',
      href: 'https://廄訂構.sejie8.de/%e7%9f%af%e6%92%a3%e7%b3%be%e7%af%84',
    },
    {
      label: '花心吧',
      href: 'https://鷹貿網2.huaxin8.irish/檸鍁窮權雖',
    },
  ],
};
